-- I actually clicked the tables together in the supabase webapp editor sorry ._.'
create table clans (
    id bigint generated by default as identity primary key,
    name text not null,
    description text,
    blood bigint,
    money bigint,
    notoriety bigint,
    influence bigint,
    user_id bigint not null references auth.users
);

ALTER TABLE
    clans ENABLE ROW LEVEL SECURITY;

create table vampires (
    id bigint generated by default as identity primary key,
    name text,
    max_blood bigint,
    current_blood bigint,
    max_health bigint,
    cvurrent_health bigint,
    clan_id bigint not null references public.clans
)
ALTER TABLE
    clans ENABLE ROW LEVEL SECURITY;